import Head from 'next/head';
import { Key } from '@/modules/game/components/Keyboard/Key';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Testing a basic functionality :D</h1>
      <div style={{display: 'flex', margin: '20px', gap: "10px"}}> 
      <Key/>
      <Key/>
      <Key/>
      <Key/>
      <Key/>
      </div>
    </>
  );
}
