name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - feature/*
      - fix/*
env:
  SONAR_ORGANIZATION: ${{ github.context.SONAR_ORGANIZATION }}
  SONAR_ORGANIZATION2: ${{ github.context.SONAR.SONAR_ORGANIZATION }}
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}