name: Unit and Integration Tests Execution

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: install dependencies
        run: pnpm install
      - name: run build
        run: pnpm run build
      - name: run tests
        run: pnpm run test
