name: WorkFlow Pull Request
on: 
  pull_request:
  push:
    branches:
      - development

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yaml
  sonar:
    secrets: inherit
    uses: ./.github/workflows/sonar.yaml
  deploy-dev:
    # needs: [unit-test, sonar]
    secrets: inherit
    uses: ./.github/workflows/deploy-dev.yaml
   
     