name: WorkFlow Main
on: pull_request

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yaml
  sonar:
    secrets: inherit
    uses: ./.github/workflows/sonar.yaml
  deploy-dev:
    needs: [unit-test, sonar]
    secrets: inherit
    uses: ./.github/workflows/deploy-dev.yaml
    if: ${{ github.ref != 'refs/heads/main' }}
  deploy-prod:
    needs: [unit-test, sonar]
    secrets: inherit
    uses: ./.github/workflows/deploy-prod.yaml
    if: ${{ github.ref == 'refs/heads/main' }}
     